function findUserByName(name) {
    return new Promise((resolve, reject) => {
        let attempts = 0;

        const retryFind = () => {
            attempts++;
            console.log(`Tentativa ${attempts}`);

            User.findOne({ name: name }).then(user => {
                if (user) {
                    resolve(user);
                } else {
                    if (attempts >= 10) {
                        reject(new Error('Número máximo de tentativas alcançado'));
                    } else {
                        setTimeout(retryFind, 1000);
                    }
                }
            }).catch(error => {
                reject(error);
            });
        };

        retryFind();
    });
}
